// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Banco descartavel onde o Prisma replica as migrations para calcular o
    // diff. Necessario para `migrate diff --from-migrations` e para o
    // `migrate dev` quando o usuario do banco nao pode criar databases.
    //
    // So passa quando tem valor: string vazia e uma URL invalida, e o Prisma
    // recusa com P1013 mesmo em comandos que nem usam shadow database.
    ...(process.env["SHADOW_DATABASE_URL"]
      ? { shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"] }
      : {}),
  },
});
